<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Blog')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>  
        
        <div class="container">           
            
            <div class="row">
                <div class="span4">
                    <div class="app-caption">Personal Blog</div>
                </div>
            </div>
            
            <?php             
            
                $this->mainMenu()->setItems(array(
                    array(
                        'id' => 'home',
                        'label' => 'Home',
                        'link' => $this->url('home')
                    ),
                    array(
                        'id' => 'about',
                        'label' => 'About',
                        'link' => $this->url('about')
                    ),
                ));
            
                echo $this->mainMenu()->render($this->activeMenuItem); 
            ?>
            
            <?php echo $this->pageBreadcrumbs()->render(); ?>
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Your Company. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
