<?php
$this->headTitle('Typeahead');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));

$this->headScript()->appendFile('/js/typeahead.min.js', 'text/javascript');
?>

<h1>Typeahead</h1>

<p>
    Type something in the text field below:
</p>

<input type="text" class="typeahead-devs" title="Type here"/>

<script type="text/javascript">
    
    $('input.typeahead-devs').typeahead({
        name: 'accounts',
        local: ['timtrueman', 'JakeHarding', 'vskarich']
    });
</script>