<?php
$this->headTitle('New Post');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Add Post'=>$this->url('application/default', array('controller'=>'post', 'action'=>'add'))
            ));

$form = $this->form;
$form->get('title')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Enter post title here'
    ));
$form->get('content')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Type content here',
    'rows'=>6
    ));
$form->get('tags')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'comma, separated, list, of, tags'
    ));
$form->get('status')->setAttributes(array(
    'class'=>'form-control'   
    ));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();

?>

<h1>New Post</h1>

<p>
    Please fill out the following form and click the *Create* button.
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <?php echo $this->formElement($form->get('title')); ?>
            <?php echo $this->formElementErrors($form->get('title')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('content')); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('tags')); ?>
            <?php echo $this->formElement($form->get('tags')); ?>
            <?php echo $this->formElementErrors($form->get('tags')); ?>                  
            <p class="help-block">Separate tags with comma.</p>
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('status')); ?>
            <?php echo $this->formElement($form->get('status')); ?>
            <?php echo $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>   