<?php
$this->headTitle('Manage Posts');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems(array(
            'Admin'=>$this->url('home')
            ));
?>

<h1>Manage Posts</h1>

<p>
<a class="btn btn-default" href="
    <?php echo $this->url('application/default', 
            array('controller'=>'post', 'action'=>'add')); ?>">
    New Post
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Post Title</th>
        <th>Date Created</th>
        <th>Last Modified</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($posts as $post): ?>
    
    <tr>
        <td><?php echo $post->getId(); ?></td>
        <td>
            <a href="<?php echo $this->url('application/default', 
                array('controller'=>'post', 'action'=>'view', 'id'=>$post->getId())); ?>">
                <?php echo $this->escapeHtml($post->getTitle()); ?>
            </a> 
        </td>
        <td><?php echo $post->getDateCreated(); ?></td>
        <td><?php echo $post->getDateModified(); ?></td>
        <td><?php echo $postManager->getPostStatusAsString($post); ?></td>
        <td>
            <a class="btn btn-info" href="<?php echo $this->url('application/default', 
            array('controller'=>'post', 'action'=>'edit', 'id'=>$post->getId())); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-danger" href="<?php echo $this->url('application/default', 
            array('controller'=>'post', 'action'=>'delete', 'id'=>$post->getId())); ?>">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>