<?php
$this->headTitle('Recent Posts');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));
?>

<h1>Recent Posts</h1>

<a class="btn btn-default" href="<?php echo $this->url('application/default', array('controller'=>'index', 'action'=>'add')); ?>">New Post</a>

<?php foreach($this->recentPosts as $post): ?>

<h3>
    <?php echo $this->escapeHtml($post->getTitle()); ?>
</h3>

<p>    
    <?php echo $this->escapeHtml($post->getContent()); ?>
</p>

<?php endforeach; ?>


