<?php
$this->headTitle('Posts');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));
?>

<h1>Posts</h1>

<div class="row">
    
    <div class="col-md-8">

    <?php foreach($posts as $post): ?>

    <h3>
        <a href="<?php echo $this->url('application/default', 
                array('controller'=>'post', 'action'=>'view', 'id'=>$post->getId())); ?>">
            <?php echo $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        
    <p>
        Tags: <?php echo $postManager->convertTagsToString($post); ?>    
    </p>

    <p class="comments-header">
        <?php echo $postManager->getCommentCountStr($post); ?> | 
        <a href="<?php echo $this->url('application/default', 
                array('controller'=>'post', 'action'=>'view', 'id'=>$post->getId()),
                array('fragment'=>'comment')); ?>">
            Add new comment
        </a>
    </p>

    <p>    
        <?php echo $this->escapeHtml($post->getContent()); ?>
    </p>

    <?php endforeach; ?>

    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName=>$frequency): ?>
                
                <a href="<?php echo $this->url('application/default', 
                    array('controller'=>'index', 'action'=>'index'),
                    array('query'=>array('tag'=>$tagName))); ?>">                   
        
                    <span style="font-size:<?php echo $frequency*3 ?>em">
                        <?php echo $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


