<?php
$this->headTitle('Downloads');

$this->mainMenu()->setActiveItemId('downloads');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Download'=>$this->url('application/default', array('controller'=>'index', 'action'=>'downloads'))
            ));
?>

<h1>Downloads</h1>

<ul>
    <li>
        <a href="<?php echo $this->url("application/default", 
            array('controller'=>'index', 'action'=>'download'), array('query'=>array('file'=>'sample.txt'))); ?>">
            sample.txt
        </a>
    </li>
</ul>