<?php
$form = $this->form;

$form->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));

$form->get('password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Your Password'
    ));

$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
    ));

$form->prepare();
?>


<div class="col-md-6 col-md-offset-2">
    
    <form name="login-form" id="login-form" class="form-horizontal" action="" method="post">
        
      <div class="form-group">
        <?php echo $this->formLabel($form->get('email')); ?>
        <?php echo $this->formElement($form->get('email')); ?>
        <?php echo $this->formElementErrors($form->get('email')); ?>     
      </div>
        
      <div class="form-group">
        <?php echo $this->formLabel($form->get('password')); ?>
        <?php echo $this->formElement($form->get('password')); ?>
        <?php echo $this->formElementErrors($form->get('password')); ?>     
      </div>
        
      <div class="form-group">
        <?php echo $this->formLabel($form->get('remember_me')); ?>
        <?php echo $this->formElement($form->get('remember_me')); ?>
        <?php echo $this->formElementErrors($form->get('remember_me')); ?>  
      </div>
        
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" name="submit" class="btn btn-default">Sign in</button>
        </div>
      </div>
        
    </form>
    
<div>