<?php

$this->headTitle('Log in');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Log in'=>$this->url('application/default', array('controller'=>'user', 'action'=>'login'))
            ));

$form = $this->form;

$form->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));

$form->get('password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Your Password'
    ));

$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
    ));

$form->prepare();

?>

<div class="row">
    <div class="col-md-6 col-md-offset-2"
        <form name="login" class="form-horizontal" action="">
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me </input>
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" name="submit" class="btn btn-default">Sign in</button>
            </div>
          </div>
        </form>
    <div>
</div>
         
<script type="text/javascript">
    
    $( document ).ready(function() {
        $( "input" ).change(function() {
            alert( "Handler for .change() called." );
        });  
    });
    
</script>