<?php

$this->headTitle('Log in');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Log in'=>$this->url('application/default', array('controller'=>'user', 'action'=>'login'))
            ));
?>

<div id="form-container" class="row">
    
    <?php 
    
    echo $this->partial('application/user/form.phtml');
    
    ?>
    
</div>
         
<script type="text/javascript">
    
    function validateFormField(form, fieldId) {
            
        $.ajax({              
              type: form.attr('method'),
              url: form.attr('action') + '?fieldId=' + fieldId,
              data: form.serialize()
            }).done(function(data, status, xhrObj) {              
                $('div#form-container').html(data);
            }).fail(function(data) {
                // Optionally alert the user of an error here...        
                alert('Error submitting form');                
            });
    }
    
    $( document ).ready(function() {
        
        $(document).on('change', 'div#form-container input', function() {            
            var form = $('form#login-form');
            var fieldId = $(this).attr("id");
        
            validateFormField(form, fieldId);
        });  
    });
    
</script>