<?php

$this->headTitle('Contact Us');

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Register'=>$this->url('application/default', array('controller'=>'user', 'action'=>'register'))
            ));

$form = $this->form;

$form->get('personal_info')->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));

$form->get('personal_info')->get('title')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));

$form->get('personal_info')->get('first_name')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'John'
    ));

$form->get('personal_info')->get('password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Your Password'
    ));

$form->get('personal_info')->get('confirm_password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Type Password Again'
    ));

$form->get('personal_info')->get('last_name')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Doe'
    ));

$form->get('address')->get('country')->setAttributes(array(
    'class'=>'form-control',     
    ));

$form->get('address')->get('city')->setAttributes(array(
    'class'=>'form-control',     
    'placeholder'=>'Your City'
    ));

$form->get('address')->get('address')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'Your Street'
    ));

$form->get('address')->get('zip_code')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'123456'
    ));

$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
    ));

$form->get('cancel')->setAttributes(array(
    'class'=>'btn btn-default'
    ));


$form->prepare();

?>

<h1>Register</h1>
<p>
    Please fill out the following form and click the <i>Create</i> 
    button to create a new account.     
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <fieldset>
            
            <legend>Personal Information</legend>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('email');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('title');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('first_name');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>

            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('last_name');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('password');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('confirm_password');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('personal_info')->get('birth_date');
                    echo $this->formLabel($element);
                    echo '<br>';
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>                        
            
        </fieldset>
            
        <fieldset>
            
            <legend>Address</legend>
          
            <div class="form-group">
                <?php 
                    $element = $form->get('address')->get('country');
                    echo $this->formLabel($element); 
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
        
            <div class="form-group">
                <?php 
                    $element = $form->get('address')->get('address');
                    echo $this->formLabel($element);
                    echo '<br>';
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('address')->get('city');
                    echo $this->formLabel($element);
                    echo '<br>';
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
            <div class="form-group">
                <?php 
                    $element = $form->get('address')->get('zip_code');
                    echo $this->formLabel($element);
                    echo '<br>';
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element); 
                ?>                  
            </div>
            
        </fieldset>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        <?php echo $this->formElement($form->get('cancel')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>    
