<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Hello World')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>  
        <div class="container">               
            <div class="row">
                <div class="col-md-4">
                            <div class="app-caption">Hello World!</div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
            <?php      
                $this->mainMenu()->setItems(array(
                    array(
                        'id' => 'home',
                        'label' => 'Home',
                        'link' => $this->url('home')
                    ),
                    array(
                        'id' => 'downloads',
                        'label' => 'Downloads',
                        'link' => $this->url("application/default", 
                                        array('controller'=>'index', 'action'=>'downloads'))
                    ),
                    array(
                        'id' => 'support',
                        'label' => 'Support',
                        'link' => $this->url('doc', array('page'=>'contents'))
                    ),
                    array(
                        'id' => 'about',
                        'label' => 'About',
                        'link' => $this->url('about')
                    ),
                ));

                echo $this->mainMenu()->render($this->activeMenuItem); 
            ?>
                    </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                <hr>                
                <p>
                    &copy; <?php echo date('Y') ?> by Your Company. <?php echo $this->translate('All rights reserved.') ?>
                </p>                               
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
