<?php
$this->headTitle('Images');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));
?>

<h1>Images</h1>

<p>
    This page displays the list of uploaded images.
</p>

<p>
    <a href="<?php echo $this->url('application/default', array('controller'=>'image', 'action'=>'upload')); ?>" class="btn btn-primary" role="button">Upload More</a>
</p>

<p>
    <div class="row">
        <div class="col-sm-6 col-md-4">

            <?php foreach($files as $file): ?>  

            <div class="thumbnail">
                <img data-src="/upload/<?php echo $file; ?>">
                <div class="caption">
                    <h3><?php echo $file; ?></h3>                    
                    <p>
                        <a href="#" class="btn" role="button">Preview</a>
                    </p>
                </div>
            </div>
            
            <?php endforeach; ?>
        </div>
    </div>
</p>

<p>
    <a href="<?php echo $this->url('application/default', array('controller'=>'image', 'action'=>'upload')); ?>" class="btn btn-primary" role="button">Upload More</a>
</p>
