<?php
$this->headTitle('Upload a New Image');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));

$form = $this->form;
$form->get('file-name')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Type new image name here'
    ));
//$form->get('overwrite-existing')->setAttributes(array(
//    'class'=>'form-control',     
//    ));
$form->get('file')->setAttributes(array(
    'class'=>'form-control',     
    
    ));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
?>

<h1>Upload a New Image</h1>

<p>
    Please fill out the following form and press the <i>Upload</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('file-name')); ?>
            <?php echo $this->formElement($form->get('file-name')); ?>
            <?php echo $this->formElementErrors($form->get('file-name')); ?>                  
        </div>
        
        <div class="checkbox">
            <?php echo $this->formLabel($form->get('overwrite-existing')); ?>
            <?php echo $this->formElement($form->get('overwrite-existing')); ?>
            <?php echo $this->formElementErrors($form->get('overwrite-existing')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('file')); ?>
            <?php echo $this->formElement($form->get('file')); ?>
            <?php echo $this->formElementErrors($form->get('file')); ?>                  
        </div>
        
        <?php echo $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>    