<?php

$this->headTitle('Contact Us');

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Contact Us'=>$this->url('contactus')
            ));

$form = $this->form;
$form->setAttribute('action', $this->url('contactus'));
$form->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));
$form->get('subject')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Type subject here'
    ));
$form->get('body')->setAttributes(array(
    'class'=>'form-control', 
    'rows'=>6, 
    'placeholder'=>'Type message text here'
    ));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();

?>

<h1>Contact Us</h1>
<p>
    Please fill out the following form to contact us. 
    We appreciate your feedback. 
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('subject')); ?>
            <?php echo $this->formElement($form->get('subject')); ?>
            <?php echo $this->formElementErrors($form->get('subject')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('body')); ?>
            <?php echo $this->formElement($form->get('body')); ?>
            <?php echo $this->formElementErrors($form->get('body')); ?>                  
        </div>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>    
