<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));
?>

<h1>Welcome</h1>

<p>
    This is the Form Demo application.
</p>

<ul>
    <li>
        <a href="<?php echo $this->url('contactus'); ?>">Feedback Form</a> This page shows the usage of a feedback form.
    </li>
    
    <li>
        <a href="<?php echo $this->url('application/default', array('controller'=>'image', 'action'=>'index')); ?>">Images</a>
        This page shows how to upload images with forms.
    </li>    
    <li>
        <a href="<?php echo $this->url('application/default', array('controller'=>'user', 'action'=>'register')); ?>">Register</a>
        This page demonstrates the usage of a form with fieldsets.
    </li>        
    <li>
        <a href="<?php echo $this->url('application/default', array('controller'=>'user', 'action'=>'login')); ?>">Login</a>
        This page demonstrates the usage of a log in form.
    </li>    
</ul>

