<?php $this->placeholder('content')->captureStart(); ?>

<div class="row">
    <div class="col-md-8">
    <?php echo $this->content; ?>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
		  <div class="panel-heading">
			<h3 class="panel-title">Ads</h3>
		  </div>
		  <div class="panel-body">
			<strong>Zend Framework 2 Book</strong>
			<p>Learn how to create modern web applications with PHP 
                and Zend Framework 2</p>            
            <a target="_blank" href="https://leanpub.com/using-zend-framework-2">
                Learn More
            </a>
		  </div>
		</div>
    </div>
</div>

<?php 
  $this->placeholder('content')->captureEnd(); 
  echo $this->partial('layout/layout', 
          array('content'=>$this->placeholder('content'))); 
?>

