<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Form Demo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>  
        <div class="container">               
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                            <div class="app-caption">Form Demo</div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php      
                        $this->mainMenu()->setItems(array(
                            array(
                                'id' => 'home',
                                'label' => 'Home',
                                'link' => $this->url('home')
                            ),                            
                            array(
                                'id' => 'about',
                                'label' => 'About',
                                'link' => $this->url('about')
                            ),
                            array(
                                'id' => 'contact',
                                'label' => 'Contact Us',
                                'link' => $this->url('contactus')
                            ),
                        ));

                        echo $this->mainMenu()->render(); 
                    ?>
                    </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?php echo $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?php echo $this->content; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                <hr>                
                <p>
                    &copy; <?php echo date('Y') ?> by Your Company. <?php echo $this->translate('All rights reserved.') ?>
                </p>                               
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
