<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home')
            ));
?>

<h1>Welcome</h1>

<p>
    This is the Hello World application powered by Zend Framework 2.
</p>

<p>
    You can optically recognize this app using the barcode image below:
</p>

<img src="<?php echo $this->url('application/default', 
          array('controller'=>'index', 
                'action'=>'barcode', 
                'type'=>'code39', 
                'label'=>'HELLO-WORLD')); ?>"/>

